### ISSUE TITLE
Mess Purge command error

### ISSUE THREAD

**Issue by silent-boy1** [gearbot/GearBot#253] opened 2019-07-06 18:32 UTC
if you purge mess messages. Bot will not complete the cleaning process. 
":no_entry_sign: I'm already cleaning here up in this channel, please wait until that's done before executing the clean command again"
Restarting the bot fix this but not a permanent solution

**Comment by AEnterprise** [comment] 2019-07-06 19:39
i'm gona assume this is a problem with your selfhosted bot since you mention restarting fixes it? if so please mention this in your bug reports in the future to avoid confusion

this is also missing a lot of other info i need to even begin investigating this:
- are you running the latest commit? there was a bug with the clean everywhere command that caused this but that was fixed in 6c6797bc5d71025cc5036f77a05189875a165ef7 , 
- what did you or a user using the bot do to trigger this behavior if you are running the latest version? it doesn't do this on my version
- what modifications if any have been made to your bot compared to this repo's master branch?

**Comment by silent-boy1** [comment] 2019-07-06 19:54
It's self hosted bot.

- I'm using latest Commit 
- I have used only !purge 1000 command and waited for all messages to be del and after some message it stop and if use this command its give error.
- I have made no modification
Using your bot its also same

**Comment by AEnterprise** [comment] 2019-07-07 08:01
still unable to reproduce this, it seems like you are just too impatient and that the clean actually isn't done yet, also looking at the tracker for where it is cleaning, it cleared for your channel on it's own and did not get stuck

**Closed by AEnterprise** 2019-07-07 08:01 UTC
Labels: needs more info
