### ISSUE TITLE
GearBot does not check whether "Manage Roles" is via Channel or Server.

### ISSUE THREAD

**Issue by Kitty-Therapist** [gearbot/GearBot#308] opened 2019-10-22 04:50 UTC
**Describe the bug**
When GearBot has "Manage Roles" permission, but does not have "Manage Permissions" in a specific channel, it refuses to give out the role and claims that it does not have "Manage Roles" permission even though that it does.
**Steps To Reproduce**
- Give GearBot "Manage Roles" permission by role.
- Deny GearBot "Manage Permission" in a channel called #test for example. 
- Add a random role to the whitelist, or just use a whitelisted role.
- Attempt to add the role to someone in the channel #test .

**Expected behavior**
GearBot should give the role to someone, since roles are supposed to be on server-side. Not channel-side.

**Screenshots**
https://i.imgur.com/8em65jr.png https://i.imgur.com/cmfh6uF.png

**Additional context**
This could possibly be a discord.py bug, but I am unsure of whether this can be fixed via GearBot. Figured I'd post here.

**Comment by Taarek** [comment] 2019-10-22 06:21
This is not exactly a bug, this is just how the commands checks are designed in d.py, @AEnterprise or someone will have to create special checks for this type of stuff.

**Comment by AEnterprise** [comment] 2019-10-22 08:22
thanks for the detailed report, this however is a duplicate of #294 and i am unable to reproduce anymore

**Closed by AEnterprise** 2019-10-22 08:22 UTC
Labels: bug
